# Generated by Django 5.0.4 on 2024-05-17 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=500)),
                ('school_short_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('room', models.IntegerField(default=0)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.classroom')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.school')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.classroom')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.school')),
            ],
        ),
    ]
