# Generated by Django 5.0.4 on 2024-05-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(max_length=1000),
        ),
    ]
